# Generated by Django 3.0.4 on 2020-05-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useractivity', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_time',
        ),
    ]
