# Generated by Django 3.0.4 on 2020-05-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useractivity', '0003_remove_user_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='strat_time',
            new_name='start_time',
        ),
    ]
