# Generated by Django 3.0.4 on 2020-05-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useractivity', '0004_auto_20200530_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_time',
        ),
    ]
